### ISSUE TITLE
Сannot import name 'TextField' and 'Binary'

### ISSUE THREAD

**Issue by mellfice** [app-generator/flask-admin-dashboards#1]
Hi. I don't know how to use GitHub, and I don't know where to write. I decided to write here. While installing through Docker, I encountered two problems. 

 File "/app/base/forms.py", line 8, in <module>
From wtforms import TextField, PasswordField
ImportError: cannot import name 'TextField'
 
File "/app/base/models.py", line 8, in <module>
from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary'.
 
Changing the following parameters in the code helped: 
'TextField' -> 'TextAreaField'.
''Binary'' -> 'BINARY'

Translated with www.DeepL.com/Translator (free version)

**Comment by app-generator** [comment]
Hello @CopyBook-Maxim 

Ty for using our products. 
Can you point us to the product that bumps this error?
